docker-compose-yaml: docker-compose.yml

project: splash-awards-ch

tasks:

  post-rollout:
    - run:
        name: env variables
        command: env
        service: cli
    - run:
        name: IF no Drupal installed drush si with no email sending
        command: |
            if ! drush status --fields=bootstrap | grep -q "Successful"; then
                # no drupal installed, we install drupal from scratch
                drush si minimal -y --sites-subdir=default --config-dir="../config/sync" --account-name=admin --account-pass=adm1n
            fi
        service: cli
        shell: bash
    - run:
        name: drush cim
        command: drush -y cim
        service: cli
    - run:
        name: drush updb
        command: drush -y updb
        service: cli
    - run:
        name: drush cr
        command: drush -y cr
        service: cli


environments:
  master:
    cronjobs:
      - name: drush cron
        schedule: "*/15 * * * *"
        command: drush cron
        service: cli
    routes:
      - nginx:
          - splashawards.ch
          - splashawards.li
          - "www.splashawards.ch":
              tls-acme: 'true'
              insecure: Redirect
          - "www.splashawards.li":
              tls-acme: 'true'
              insecure: Redirect
