third_party_settings:
  ds:
    regions:
      bottom:
        - scroll_to_field
    fields:
      scroll_to_field:
        plugin_id: scroll_to_field
        weight: 5
        label: hidden
        formatter: default
        settings:
          scroll_to_identifier: subscribe-now
          button_text: 'Subscribe for this event'
  field_group:
    group_below_paragraph_header:
      children:
        - scroll_to_field