dependencies:
  config:
    - webform.webform.event_subscription
  module:
    - webform
variant_settings:
  blocks:
    2e6bc2dc-bf68-4f8f-ae4a-5c78bd70571d:
      id: webform_block
      label: Webform
      provider: webform
      label_display: '0'
      webform_id: event_subscription
      default_data: ''
      region: footer
      weight: 0
      uuid: 2e6bc2dc-bf68-4f8f-ae4a-5c78bd70571d
      context_mapping: {  }
