layout_plugin.settings.rocketship_layout_2col:
  type: layout_plugin.settings
  label: 'Settings for 2 col stacked layout'
  mapping:
    layout_reversed:
      type: boolean
      label: 'Layout reversed'
