plugin.plugin_configuration.search_api_backend.search_api_solr:
  type: config_object
  label: 'Search API Solr settings'
  mapping:
    retrieve_data:
      type: boolean
      label: 'Retrieve result data from Solr'
    highlight_data:
      type: boolean
      label: 'Highlight retrieved data'
    skip_schema_check:
      type: boolean
      label: 'Skip schema verification'
    site_hash:
      type: boolean
      label: 'Restrict searches to current site'
    server_prefix:
      type: string
      label: 'The default prefix for Solr indexes on this backend'
    domain:
      type: string
      label: 'The targeted content domain'
    connector:
      type: string
      label: 'The connector plugin ID'
    connector_config:
      type: plugin.plugin_configuration.search_api_solr_connector.[%parent.connector]
    sasm_limit_search_page_to_content_language:
      type: boolean
      label: 'Limit to current content language'
    sasm_search_page_include_language_independent:
      type: boolean
      label: 'Include languages independent content in search results'
    optimize:
      type: boolean
      label: 'Optimize this backend'

plugin.plugin_configuration.search_api_backend.search_api_solr_any_schema:
  type: plugin.plugin_configuration.search_api_backend.search_api_solr
  label: 'Search API Solr Any Schema settings'
