third_party_settings:
  ds:
    regions:
      footer:
        - field_job_property_one
        - field_job_category
        - group_footer_wrapper
    fields:
      ds_time_ago:
        plugin_id: ds_time_ago
        weight: 2
        label: hidden
        formatter: default
  field_group:
    group_footer_wrapper:
      children:
        - field_job_property_one
        - field_job_category
      parent_name: ''
      weight: 1
      format_type: html_element
      format_settings:
        label: footer_wrapper
        element: div
        show_label: false
        label_element: h3
        attributes: ''
        effect: none
        speed: fast
        id: ''
        classes: 'node__meta node__meta--full node__meta--job node__meta--job-full'
      label: footer_wrapper
      region: hidden
content:
  field_job_category:
    type: entity_reference_label
    weight: 1
    region: footer
    label: inline
    settings:
      link: true
    third_party_settings: {  }
  field_job_property_one:
    type: entity_reference_label
    weight: 0
    region: footer
    label: inline
    settings:
      link: true
    third_party_settings: {  }
hidden:
  field_job_property_two: true
