third_party_settings:
  field_group:
    group_filtering:
      children:
        - field_job_property_one
        - field_job_property_two
        - field_job_category
      parent_name: ''
      weight: 2
      format_type: fieldset
      format_settings:
        id: ''
        classes: ''
        description: ''
        required_fields: true
      label: Filtering
      region: content
content:
  field_job_category:
    weight: 21
    settings: {  }
    third_party_settings: {  }
    type: options_select
    region: content
  field_job_property_two:
    weight: 20
    settings: {  }
    third_party_settings: {  }
    type: options_select
    region: content
  field_job_property_one:
    weight: 19
    settings: {  }
    third_party_settings: {  }
    type: options_select
    region: content
