third_party_settings:
  ds:
    regions:
      content:
        - group_teaser_bottom
        - field_job_property_one
        - field_job_category
      second:
        - group_actions
        - node_link
        - ds_time_ago
    fields:
      ds_time_ago:
        plugin_id: ds_time_ago
        weight: 6
        label: hidden
        formatter: default
      node_title:
        plugin_id: node_title
        weight: 0
        label: hidden
        formatter: default
        settings:
          link: true
          wrapper: h3
          class: ''
  field_group:
    group_actions:
      children:
        - node_link
        - ds_time_ago
      parent_name: ''
      weight: 2
      format_type: html_element
      format_settings:
        id: ''
        classes: 'node__actions node__actions--teaser node__actions--job node__actions--job-teaser'
        element: div
        show_label: false
        label_element: h3
        attributes: ''
        effect: none
        speed: fast
      label: Actions
      region: hidden
    group_teaser_bottom:
      children:
        - field_job_property_one
        - field_job_category
      parent_name: ''
      weight: 3
      format_type: html_element
      format_settings:
        label: 'teaser bottom'
        element: div
        show_label: false
        label_element: h3
        attributes: ''
        effect: none
        speed: fast
        id: ''
        classes: 'node__meta node__meta--teaser node__meta--job node__meta--job-teaser'
      label: 'teaser bottom'
      region: content
id: node.job.teaser
targetEntityType: node
bundle: job
mode: teaser
content:
  field_job_category:
    type: entity_reference_label
    weight: 5
    region: content
    label: inline
    settings:
      link: true
    third_party_settings: {  }
  field_job_property_one:
    type: entity_reference_label
    weight: 4
    region: content
    label: inline
    settings:
      link: true
    third_party_settings: {  }
hidden:
  field_job_property_two: true
