third_party_settings:
  ds:
    regions:
      content:
        - group_header_wrapper
        - field_canonical_image
        - field_node_title_replacement
        - ds_time_ago
      bottom:
        - group_meta
        - field_job_property_one
        - field_job_category
        - scroll_to_field
    fields:
      scroll_to_field:
        plugin_id: scroll_to_field
        weight: 5
        label: hidden
        formatter: default
        settings:
          scroll_to_identifier: apply-to
          button_text: 'Apply for this job'
  field_group:
    group_meta:
      children:
        - field_job_property_one
        - field_job_category
        - scroll_to_field
      parent_name: ''
      weight: 2
      format_type: html_element
      format_settings:
        label: meta
        element: div
        show_label: false
        label_element: h3
        attributes: ''
        effect: none
        speed: fast
        id: ''
        classes: 'node__meta node__meta--header node__meta--job node__meta--job-header'
      label: meta
      region: bottom
id: node.job.header
targetEntityType: node
bundle: job
mode: header
content:
  field_job_category:
    type: entity_reference_label
    weight: 4
    region: bottom
    label: inline
    settings:
      link: true
    third_party_settings: {  }
  field_job_property_one:
    type: entity_reference_label
    weight: 3
    region: bottom
    label: inline
    settings:
      link: true
    third_party_settings: {  }
hidden:
  field_job_property_two: true
