variant_settings:
  blocks:
    2b578010-b42f-4be9-95a2-ec766af8e2aa:
      id: webform_block
      label: 'Apply for this job'
      provider: webform
      label_display: visible
      webform_id: apply_for_this_job
      default_data: ''
      region: footer
      weight: -1
      uuid: 2b578010-b42f-4be9-95a2-ec766af8e2aa
      context_mapping: {  }