third_party_settings:
  ds:
    regions:
      footer:
        - office_more_offices
    fields:
      office_more_offices:
        plugin_id: office_more_offices
        weight: 7
        label: hidden
        formatter: default