dependencies:
  config:
    - field.field.node.news.field_news_tags
third_party_settings:
  ds:
    regions:
      content:
        - field_news_tags
        - group_filters
  field_group:
    group_actions:
      children:
        - group_filters
    group_filters:
      children:
        - field_news_tags
      parent_name: group_actions
      weight: 6
      format_type: html_element
      format_settings:
        id: ''
        classes: 'node__filters node__filters--teaser node__filters--news node__filters--news-teaser'
        element: div
        show_label: false
        label_element: h3
        attributes: ''
        effect: none
        speed: fast
      label: Filters
      region: content
content:
  field_news_tags:
    type: entity_reference_label
    weight: 6
    region: content
    label: hidden
    settings:
      link: true
    third_party_settings: {  }