dependencies:
  config:
    - field.field.node.news.field_news_tags
third_party_settings:
  ds:
    regions:
      bottom:
        - group_filters
        - field_news_tags
  field_group:
    group_news_meta:
      children:
        - group_filters
    group_filters:
      children:
        - field_news_tags
      parent_name: group_news_meta
      weight: 5
      format_type: html_element
      format_settings:
        id: ''
        classes: 'node__filters node__filters--full node__filters--news node__filters--news-full'
        element: div
        show_label: false
        label_element: h3
        attributes: ''
        effect: none
        speed: fast
      label: Filters
      region: hidden
content:
  field_news_tags:
    type: entity_reference_label
    weight: 6
    region: bottom
    label: hidden
    settings:
      link: true
    third_party_settings: {  }
