dependencies:
  config:
    - field.field.node.news.field_news_tags
third_party_settings:
  ds:
    regions:
      second:
        - field_news_tags
        - group_filters
  field_group:
    group_meta:
      children:
        - group_filters
    group_filters:
      children:
        - field_news_tags
      parent_name: group_meta
      weight: 10
      format_type: html_element
      format_settings:
        label: 'More about'
        element: div
        show_label: true
        label_element: h3
        attributes: ''
        effect: none
        speed: fast
        id: ''
        classes: 'node__filters node__filters--full node__filters--news node__filters--news-full'
      label: 'More about'
      region: hidden
content:
  field_news_tags:
    type: entity_reference_label
    weight: 2
    region: second
    label: hidden
    settings:
      link: true
    third_party_settings:
      ds:
        ds_limit: ''