name: 'Configuration Provider'
type: module
description: 'Enables provision of configuration by extensions.'
# core: 8.x
package: Config
dependencies:
 - 'drupal:config'

# Information added by Drupal.org packaging script on 2018-09-20
version: '8.x-2.0-alpha6'
core: '8.x'
project: 'config_provider'
datestamp: 1537468385
