dependencies:
  config:
    - field.field.node.product.field_product_category
    - field.field.node.product.field_product_property_one
    - field.field.node.product.field_product_property_two
    - field.field.node.product.field_product_related_products
third_party_settings:
  ds:
    regions:
      content:
        - field_product_category
        - field_product_property_one
        - group_info
        - field_product_property_two
        - field_product_attributes
  field_group:
    group_info:
      children:
        - field_product_category
        - field_product_property_one
        - field_product_property_two
        - field_product_attributes
      parent_name: ''
      weight: 2
      format_type: html_element
      format_settings:
        id: ''
        classes: 'node__info node__info--teaser node__info--product node__info--product-teaser'
        element: div
        show_label: false
        label_element: h3
        attributes: ''
        effect: none
        speed: fast
      label: Info
      region: content
content:
  field_product_attributes:
    type: label_value_formatter
    weight: 3
    region: content
    label: hidden
    settings:
      show_only_promoted: '1'
    third_party_settings:
      ds:
        ds_limit: '1'
  field_product_category:
    type: entity_reference_label
    weight: 0
    region: content
    label: inline
    settings:
      link: true
    third_party_settings: {  }
  field_product_property_one:
    type: entity_reference_label
    weight: 1
    region: content
    label: inline
    settings:
      link: true
    third_party_settings: {  }
  field_product_property_two:
    type: entity_reference_label
    weight: 2
    region: content
    label: inline
    settings:
      link: true
    third_party_settings: {  }
hidden:
  field_product_related_products: true
  field_product_teaser: true
