dependencies:
  config:
    - field.field.node.product.field_product_category
    - field.field.node.product.field_product_property_one
    - field.field.node.product.field_product_property_two
    - field.field.node.product.field_product_related_products
    - node.type.product
third_party_settings:
  ds:
    regions:
      content:
        - field_product_category
        - field_product_property_one
        - field_product_property_two
      bottom:
        - field_product_related_products
  field_group:
    group_info:
      children:
        - field_product_category
        - field_product_property_one
        - field_product_property_two
content:
  field_product_category:
    type: entity_reference_label
    weight: 0
    region: content
    label: inline
    settings:
      link: true
    third_party_settings: {  }
  field_product_property_one:
    type: entity_reference_label
    weight: 1
    region: content
    label: inline
    settings:
      link: true
    third_party_settings: {  }
  field_product_property_two:
    type: entity_reference_label
    weight: 2
    region: content
    label: inline
    settings:
      link: true
    third_party_settings: {  }
  field_product_related_products:
    type: related_reference_entity_view
    weight: 6
    region: bottom
    label: above
    settings:
      view_mode: related
      between_fields_conjunction: OR
      sort: created
      sort_direction: DESC
      limit: '-1'
      force_padding: '1'
      reference_selection_fields: {  }
      link: false
    third_party_settings:
      ds:
        ds_limit: ''