dependencies:
  config:
    - field.field.node.blog.field_blog_tags
third_party_settings:
  ds:
    regions:
      bottom:
        - field_blog_tags
  field_group:
    group_blog_meta:
      children:
        - field_blog_tags
content:
  field_blog_tags:
    type: entity_reference_label
    weight: 5
    region: bottom
    label: hidden
    settings:
      link: true
    third_party_settings: {  }