dependencies:
  config:
    - field.field.node.blog.field_blog_tags
third_party_settings:
  ds:
    regions:
      content:
        - field_blog_tags
content:
  field_blog_tags:
    type: entity_reference_label
    weight: 2
    region: content
    label: hidden
    settings:
      link: true
    third_party_settings:
      ds:
        ds_limit: ''
hidden:
  field_meta_tags: true