dependencies:
  config:
    - field.field.node.blog.field_blog_tags
third_party_settings:
  field_group:
    group_extra:
      children:
        - field_blog_tags
      parent_name: ''
      weight: 2
      format_type: fieldset
      format_settings:
        id: ''
        classes: ''
        description: ''
        required_fields: true
      label: Extra
      region: content
content:
  field_blog_tags:
    weight: 4
    settings: {  }
    third_party_settings: {  }
    type: options_select
    region: content