dependencies:
  config:
    - field.field.node.blog.field_blog_tags
third_party_settings:
  ds:
    regions:
      footer:
        - field_blog_tags
content:
  field_blog_tags:
    type: entity_reference_label
    weight: 5
    region: footer
    label: hidden
    settings:
      link: true
    third_party_settings: {  }