dependencies:
  config:
    - page_manager.page.node_view
    - views.view.related_blogs
  module:
    - ctools
    - panels
    - views
variant_settings:
  blocks:
    1f47a99e-329f-44f4-8bba-63c839734ab3:
      id: 'views_block:related_blogs-related_blog_items'
      label: ''
      provider: views
      label_display: '0'
      views_label: ''
      items_per_page: none
      region: cta_02
      weight: 0
      uuid: 1f47a99e-329f-44f4-8bba-63c839734ab3
      context_mapping: {  }